### ISSUE TITLE
golden-ratio won't work with ace-window package

### ISSUE THREAD

**Issue by xmaillard** [roman/golden-ratio.el#42]
Hello,

Read about golden-ratio on the Internet which I found could be usefull stuff. Tried it but it did not work at first.

I had to manually do a one-call to golden-ratio RET to make it works and then, I had to C-x o to make it really working with my setup. When trying to navigate from buffer to buffer using the excellent ace-window package did nothing.

What can I do ?

"GNU Emacs 25.0.50.1 (x86_64-apple-darwin14.0.0, NS appkit-1343.16 Version 10.10.1 (Build 14B25))
 of 2014-12-17 on kcals.intra.maillard.im"

 '(golden-ratio-exclude-modes
   (quote
    ("eshell-mode" "diff-mode" "dired-mode" "ediff-mode")))
 '(golden-ratio-mode t)

Nothing more.

Thank you

**Comment by xmaillard** [comment]
Link to that package:

git@github.com:abo-abo/ace-window.git

As far as I can tell, ace-window is using other-window command when there are only 2 windows. So golden-ratio works in that situation. It failed as soon as the window counter is > 2

Like really much this mode !

Regards

**Comment by thierryvolpiatto** [comment]
Xavier Maillard <notifications@github.com> writes:

> What can I do ?

(add-to-list 'golden-ratio-extra-commands 'aw--callback)

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by xmaillard** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> Xavier Maillard <notifications@github.com> writes:
>
>> What can I do ?
>
> (add-to-list 'golden-ratio-extra-commands 'aw--callback)

Done. Worked like a charme.

Thank you Thierry (long time no see by the way ;)).

Xavier
--
Sent with my mu4e

**Comment by yi-tang** [comment]
Hi all,

I tried to add 

`(add-to-list 'golden-ratio-extra-commands 'aw--callback)` 

to my .emacs, but ace-window still does not trigger golden-ratio.

**Comment by conorbev** [comment]
Try:
```
(add-to-list 'golden-ratio-extra-commands 'ace-window)
```
That is working for me with both the melpa-stable and melpa versions of ace-window

**Comment by xmaillard** [comment]
conorbev <notifications@github.com> writes:

> Try:
> ```
> (add-to-list 'golden-ratio-extra-commands 'ace-window)
> ```
> That is working for me with both the melpa-stable and melpa versions of ace-window

I confirm, this is what I have too.
-- Xavier.

**Comment by yi-tang** [comment]
@conorbev @xmaillard it works now, thank you very much.
